apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    # region must be one of the AWS available regions: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regions
    region: us-east-1
    registry: ghcr.io
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: bucketrepo
  secretStorage: local
  storage:
  - name: logs
  # other url formats such as s3://minio-1611088947.minio.svc.cluster.local/jx3-logs and s3://minio-1611088947.minio.svc.cluster.local were previously tried but didn't seem to work
    url: "s3://jx3-logs?endpoint=minio-1611088947.minio.svc.cluster.local:9000&disableSSL=true&s3ForcePathStyle=true&region=ignored"
  vault: {}
  webhook: lighthouse
